### ISSUE TITLE
how can i compile it locally

### ISSUE THREAD

**Issue by qkmaosjtu** [emanuele-f/PCAPdroid-mitm#1]
![image](https://user-images.githubusercontent.com/16631352/164966050-4e0677e2-fcad-4a15-abd0-6492f43be7bb.png)

**Comment by emanuele-f** [comment]
The plugin is installed automatically from the [chaquopy maven repo](https://github.com/emanuele-f/PCAPdroid-mitm/blob/master/settings.gradle#L3), so this seems an issue with your build environment. You can find more info here: https://chaquo.com/chaquopy/doc/current/android.html

**Comment by emanuele-f** [comment]
No feedback received, closing
