### ISSUE TITLE
Bad PCAPdroid mitm version. Uninstall it and retry.

### ISSUE THREAD

**Issue by 2011** [emanuele-f/PCAPdroid-mitm#10]
Have PCAPdroid 1.6.4. Installed latest (0.15) PCAPdroid mitm. In the Mitm setup wizard, when I select "next" at the bottom of the page, I get the above message.

**Comment by warren-bank** [comment]
sorry to chime in, but I was meaning to ask about that as well..

* PCAPdroid [v1.6.4](https://github.com/emanuele-f/PCAPdroid/releases/tag/v1.6.4) will only run with PCAPdroid-mitm [v0.14](https://github.com/emanuele-f/PCAPdroid-mitm/releases/tag/v0.14)
* PCAPdroid [v1.6.5](https://github.com/emanuele-f/PCAPdroid/releases/tag/v1.6.5) will only run with PCAPdroid-mitm [v0.15](https://github.com/emanuele-f/PCAPdroid-mitm/releases/tag/v0.15)

How tightly coupled are the versions of the two apps?
Is there a legitimate need for such strict restrictions?

**Comment by warren-bank** [comment]
specifically..

* [code](https://github.com/emanuele-f/PCAPdroid/blob/v1.6.4/app/src/main/java/com/emanuelef/remote_capture/fragments/mitmwizard/InstallAddon.java#L40-L43):
  ```java
    if(MitmAddon.isInstalled(requireContext()))
      addonOk();
    else
      installAddon();
  ```
* [code](https://github.com/emanuele-f/PCAPdroid/blob/v1.6.4/app/src/main/java/com/emanuelef/remote_capture/MitmAddon.java#L51):
  ```java
    public static final long PACKAGE_VERSION_CODE = 14;
  ```
* [code](https://github.com/emanuele-f/PCAPdroid/blob/v1.6.4/app/src/main/java/com/emanuelef/remote_capture/MitmAddon.java#L119-L121):
  ```java
    public static boolean isInstalled(Context ctx) {
      return getInstalledVersion(ctx) == PACKAGE_VERSION_CODE;
    }
  ```
* [code](https://github.com/emanuele-f/PCAPdroid/blob/v1.6.4/app/src/main/java/com/emanuelef/remote_capture/fragments/mitmwizard/InstallAddon.java#L58-L73):
  ```java
    private void installAddon() {
      long installed_ver = MitmAddon.getInstalledVersion(requireContext());

      if(installed_ver < 0) {
        mStepLabel.setText(R.string.install_the_mitm_addon);  // "Install the PCAPdroid <a>mitm addon</a>"
        mStepButton.setText(R.string.install_action);
      } else if(installed_ver < MitmAddon.PACKAGE_VERSION_CODE) {
        mStepLabel.setText(R.string.mitm_addon_new_version);  // "The PCAPdroid mitm addon must be upgraded"
        mStepButton.setText(R.string.upgrade_action);
      } else {
        mStepLabel.setText(R.string.mitm_addon_bad_version);  // "Bad PCAPdroid mitm addon version. Uninstall it and retry"
        mStepIcon.setColorFilter(mDangerColor);
        mStepButton.setText(R.string.install_action);
        mStepButton.setEnabled(false);
        return;
      }
    }
  ```

**Comment by emanuele-f** [comment]
The supported method to install the mitm addon is via the PCAPdroid app, which will download the correct version of it. With a recent contribution, PCAPdroid will also show the required version number in the ui.

The requirement to have the exact mitm addon version installed is here mainly for ease of development. In particular, the mitm addon api may change and I don't provide any kind of compatibility with older versions.
