### ISSUE TITLE
Pcapdroid mitm setupwizard failure: bad addon version

### ISSUE THREAD

**Issue by skeptronus** [emanuele-f/PCAPdroid-mitm#11]
Mitm setup wizard from pcapdroid settings page fails.
Error message: bad mitm addon version. Please install version 0.15 and retry.
Pcapdroid version: 1.6.9
Mitm addon version: 0.16
Both installed from f-droid. Android 13

**Comment by emanuele-f** [comment]
Yes, latest addon version it's only a preview
