### ISSUE TITLE
Error: connection to the mitm add-on failed 

### ISSUE THREAD

**Issue by windowshopr** [emanuele-f/PCAPdroid-mitm#12]
![Screenshot_20240111-094008](https://github.com/emanuele-f/PCAPdroid-mitm/assets/40477419/b88b2ebb-9f3b-4ba6-9617-cbcecfbba3b2)

I have added both mitm and pcapdroid to the "not optimized" list of battery background optimized apps. Same error. Could be the android version 10 I'm running on the unihertz titan, but thought id check for some troubleshooting.

**Comment by emanuele-f** [comment]
Have you open the mitm addon app, keeping it in the recent apps while switching to PCAPdroid? Your rom may have additional settings to prevent interfering with background apps, this is your best bet, as there are no other known workarounds

**Comment by windowshopr** [comment]
Unfortunately yes i have it running in the with no other restrictions in the settings. Darn! Thanks anyway!
