### ISSUE TITLE
where to get help?

### ISSUE THREAD

**Issue by grizlyadams** [emanuele-f/PCAPdroid-mitm#13]
Hi, apologies if this is not the correct place to ask about PCAPdroid-mitm, but I can see no other way of asking.

Is there a more appropriate place to ask a question?

Thanks, and apologies once again if this is not the correct place.

**Comment by emanuele-f** [comment]
Hello, for development questions you can ask here. For other questions (e.g. usage) you can ask on the official telegram group https://t.me/PCAPdroid

**Comment by grizlyadams** [comment]
thanks!
