### ISSUE TITLE
You have issues. WELL SO DO I

### ISSUE THREAD

**Issue by STOPthefckinMITM** [emanuele-f/PCAPdroid-mitm#15]
@hhhaiai 
Need
help. Stat 

@emanuele-f  i was the subject of your attack earlier. I hope to god you have a) way to fix the cluster fsck of a mess on my phone b) a CVE to make me feel better about the time amd embarrassment for getting hacked. 

Im worried that if i reboot the phone, its going to be fooked for good, thanks to those lovely presents you left. Im no coder, but im well aware that this presents a real challenge

Please, its urgent. My girlfriend wants her phone back 

@hhhaiai #11

**Comment by STOPthefckinMITM** [comment]
No. Im being serious
Not funny. I am not equipped to deal with the loss of data and my device

**Comment by STOPthefckinMITM** [comment]
At very least, i need to know that the attack is halted and that my personal information, and security details will be disclosed and resolved. Right now tho, im at a loss

**Comment by STOPthefckinMITM** [comment]
Gimme  a break will you. Im not in it and never used git. How the hell should i know where to post or how to keep my head drom e
xploding ,, , where's the janirator @emanuele-f

**Comment by emanuele-f** [comment]
I don't know how to reply to you, I hope this is a joke, like a delayed 1st of April. If not, get some help. PCAPdroid does not modify phone system data, so your claims are not founded. As it's open source, feel free to review it
