### ISSUE TITLE
VT screaming

### ISSUE THREAD

**Issue by IzzySoft** [emanuele-f/PCAPdroid-mitm#18]
Looks like [VT](https://www.virustotal.com/gui/file/bcf54e5c939ffc4bf39c49f8190dd45c36bfc4180a3fdc6e6d7573cf39fd23c3/detection/f-bcf54e5c939ffc4bf39c49f8190dd45c36bfc4180a3fdc6e6d7573cf39fd23c3-1729099949) doesn't like the latest release: 7 out of 67 engines flagged the APK. Unfortunately, and as usual, details are rather non-existent – but I thought to let you know…

**Comment by emanuele-f** [comment]
Hi @IzzySoft , thanks for reporting.
I will try to drill down, maybe some new python native module is triggering this

**Comment by IzzySoft** [comment]
Thanks for the swift response – and best luck identifying/eliminating the culprit :crossed_fingers:

**Comment by emanuele-f** [comment]
For an unlucky circumstance zipping the [mitmweb app.js](https://github.com/mitmproxy/mitmproxy/blob/v11.0.0/mitmproxy/tools/web/static/app.js) file generates a [malicious signature](https://www.virustotal.com/gui/file/f163aa17bd93edf0d5275a933a81966f4a91d3b62f3045e9e8c31c3f344eacb4/detection). Adding [a newline](https://github.com/emanuele-f/mitmproxy/commit/25fee916f64f7bc13d6474e445c763aa17d796a0) to `app.js` fixes this.

I've generated the [v1.4 release](https://github.com/emanuele-f/PCAPdroid-mitm/releases/tag/v1.4) with the fix. However, the app still triggers a `RiskWare/Win32.Kryptik.a` from Antiy-AVL. This one is related to the python cryptography `_rust.so` module. This one seems a temporary misdetection, as it's also triggered on older PCAPdroid-mitm builds if reanalyze is triggered, so I think we should just ignore it. @IzzySoft what do you think?

**Comment by IzzySoft** [comment]
> For an unlucky circumstance zipping the [mitmweb app.js](https://github.com/mitmproxy/mitmproxy/blob/v11.0.0/mitmproxy/tools/web/static/app.js?rgh-link-date=2024-10-27T17%3A47%3A03Z) file generates a [malicious signature](https://www.virustotal.com/gui/file/f163aa17bd93edf0d5275a933a81966f4a91d3b62f3045e9e8c31c3f344eacb4/detection). Adding [a newline](https://github.com/emanuele-f/mitmproxy/commit/25fee916f64f7bc13d6474e445c763aa17d796a0) to app.js fixes this.

Oof!

> However, the app still triggers a RiskWare/Win32.Kryptik.a from Antiy-AVL.

Well, 1 out of 65 clearly is a "false alert" (especially as that seems to be a "lesser engine", not one of the "major ones"). And it says "Win32", well… Everything < 5 to me is. But 7 was over the threshold, so I had to let you know.

> so I think we should just ignore it

I fully agree. Thanks for digging in & fixing up, and interesting findings! Snakeoil… :speak_no_evil: :dash:
