### ISSUE TITLE
Not compatible with Android Go

### ISSUE THREAD

**Issue by REmerald** [emanuele-f/PCAPdroid-mitm#20]
The app from the main repo works, but the PCAPdroid-mitm refuses to install, installer says it's not compatible, tried through f-droid, it says INSTALL_FAILED_NO_MATCHING_ABIS.

**Comment by emanuele-f** [comment]
Hello, you should install the apk matching your device ABI. Normally it's arm64-v8a https://github.com/emanuele-f/PCAPdroid-mitm/releases/download/v1.4/PCAPdroid-mitm_v1.4_arm64-v8a.apk

**Comment by REmerald** [comment]
@emanuele-f I downloaded arm64-v8a from the releases, and as I previously mentioned, I even tried to install it through f-droid (IzzyOnDroid repo) and it said that it was incompatible too.

**Comment by emanuele-f** [comment]
That's weird, it runs on Android 14 for me. If you have adb, maybe looking at logcat can give more infoes on the installation failure

**Comment by REmerald** [comment]
@emanuele-f I found out why, for some reason this phone (released in 2024) uses Android Go with
```
$ adb shell getprop ro.product.cpu.abi
armeabi-v7a
```
even though it has plenty of ram (there are only 3 and 4 gb ram variants of the model) and the cpu has 64-bit support.
Like what the actual f.
