### ISSUE TITLE
How to install cacert on work profile

### ISSUE THREAD

**Issue by otuva** [emanuele-f/PCAPdroid-mitm#4]
I use pcapdroid in lineageos work profile but can't seem to install exported cacert for TLS decryption for my work profile.

--- 

This was a draft and I figured it out after hours of pain, eventually. 
So Instead of discarding I wanted to share the solution.

And it appears that Installing a cacert on work profile is not something worthwhile for mitm because apps [won't trust user](https://emanuele-f.github.io/PCAPdroid/tls_decryption) certs anyway. But anyways 

To install a user ca certificate into work profile you will need root access.

### Installing user certificates into work profile:

 1. Install an exported certificate normal way
 2. Get a root shell

```
adb root; adb shell
```

 3. Verify certificate and hash is installed.

```
# an example would be 1000_CACERT_*
ls /data/misc/keystore/user_0/<CACERT>
```

```
# example: 81c450f1.0
ls /data/misc/user/0/cacerts-added/<xxxxxxxx.0>
```

 4. Move them to the work profile

```
cd /data/misc/keystore/
mv user_0/<CACERT> user_10/
```
```
cd /data/misc/user
mkdir 10/cacerts-added
mv 0/cacerts-added/<xxxxxxxx.0> 10/cacerts-added/
```

**Comment by emanuele-f** [comment]
Thanks for sharing these instructions, they may be useful. Since you have root, have you tried installing the certificate as a system certificate in the system root (`/system/etc/security/cacerts`)? Is it accepted by the work profile?

**Comment by otuva** [comment]
I've never tried that actually. 

I needed magisk for something else and I figured why not just install the trust cert module if I have magisk. 

And the module installs the certificate for both profiles system-wise whether it's under the work or normal profile of standard user so you can disable or enable separately. 

What I don't know is that if the module installs cacerts separately or there's only one system certificate handle and android system  allows you to enable/disable independently. If I try to explore I can edit or add a new comment about that too.

**Comment by emanuele-f** [comment]
The certificate is probably installed globally (at least if you use https://github.com/NVISOsecurity/MagiskTrustUserCerts). By the way, why do you need to install the cert as a user certificate if you can install it as system? To bypass certificate transparency?

**Comment by otuva** [comment]
Decision to install magisk was after the revelation 😃. I thought it would suffice to install cert as user but apps won't trust.

**Comment by emanuele-f** [comment]
Oh I see. Closing the issue
