### ISSUE TITLE
Any plans to upgrade MITMProxy

### ISSUE THREAD

**Issue by djsan15** [emanuele-f/PCAPdroid-mitm#6]
There seems to be some bug fixes for HTTP2  in recent versions(>8.0.0) of mitmproxy among numerous feature additions. I am trying to make it work with a HTTP2 server (TLS Decrypt mode) but most of the traffic is returning in errors at MITMProxy layer like:
```
E mitmproxy: Addon error: Traceback (most recent call last):
E mitmproxy:   File "/data/data/com.pcapdroid.mitm/files/chaquopy/AssetFinder/requirements/mitmproxy/addons/dumper.py", line 275, in response
E mitmproxy:   File "/data/data/com.pcapdroid.mitm/files/chaquopy/AssetFinder/requirements/mitmproxy/addons/dumper.py", line 262, in echo_flow
E mitmproxy: AttributeError: 'StdOut' object has no attribute 'flush'
```
Wanted to check if there are any plans to support the latest mitmproxy?

**Comment by emanuele-f** [comment]
Right timing, see https://github.com/chaquo/build-wheel/issues/15#issuecomment-1404636951

**Comment by emanuele-f** [comment]
Preliminary experimental version https://t.me/PCAPdroid/20549

**Comment by emanuele-f** [comment]
Errors fixed, official release now available: https://github.com/emanuele-f/PCAPdroid-mitm/releases/tag/v0.13.

It can be tested with the latest PCAPdroid debug apk: https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.1-951234f.apk
